### ISSUE TITLE
Problem with more then 7 dimensions?

### ISSUE THREAD

**Issue by not-original** [aliasoblomov/Universal-Analytics-to-BigQuery#1]
When running this schema, the data uploads no problem. 

metrics': [
                        {'expression': 'ga:sessions'},
                        {'expression': 'ga:pageviews'},
                        {'expression': 'ga:users'},
                    ],
 'dimensions': [
                        {'name': 'ga:dateHourMinute'},                        
                        {'name': 'ga:pageTitle'},
                        {'name': 'ga:pagePath'},
                        {'name': 'ga:source'},
                        {'name': 'ga:city'},
                        {'name': 'ga:region'},
                        {'name': 'ga:deviceCategory'},
                    ]

But this schema causes an error (adding the two extra dimensions for Age and Gender).  Which reads '**__source does not have a schema._**'

metrics': [
                        {'expression': 'ga:sessions'},
                        {'expression': 'ga:pageviews'},
                        {'expression': 'ga:users'},
                        # Add or remove metrics as per your requirements
                    ],
                    #only allow nine
                    'dimensions': [
                        {'name': 'ga:dateHourMinute'},                        
                        {'name': 'ga:pageTitle'},
                        {'name': 'ga:pagePath'},
                        {'name': 'ga:source'},
                        {'name': 'ga:city'},
                        {'name': 'ga:region'},
                        {'name': 'ga:deviceCategory'},
                       **{'name': 'ga:userAgeBracket'},  
                       {'name': 'ga:userGender'},**
                    ],

Is there a limit to the amount of dimensions we can request? I thought it was 10.

**Comment by aliasoblomov** [comment]
You are correct, as I recall from the documentation, the dimension limit was 9. However, I have now checked it again and it appears that it does not allow more than 7 dimensions. To verify this, you can check the data retrieval of the API in the Google tool using this link before making any changes and running the script: https://ga-dev-tools.google/query-explorer/.
