### ISSUE TITLE
"Segmentation fault: 11" error

### ISSUE THREAD

**Issue by alexshel** [aliasoblomov/Universal-Analytics-to-BigQuery#9]
I am getting "Segmentation fault: 11" error when running the script on Mac (Big Sur).
Not sure how to debug the problem. There are no other details on the issue in Terminal window.

![image](https://github.com/aliasoblomov/Universal-Analytics-to-BigQuery/assets/11222499/e4c5b579-cd26-4f64-be80-1b9614145dd8)

Google tells this might be because "you're accessing memory you shouldn't"

**Comment by aliasoblomov** [comment]
There is no need to upload the file locally; try running the steps on Google Colab.
